/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundrydailyclean;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class KalkulasiHargaLaundry extends javax.swing.JFrame {

    /**
     * Creates new form KalkulasiHargaLaundry
     */
    String titipNama = "", titipAlamat = "", titipHP = "";
    public KalkulasiHargaLaundry() {
        initComponents();
    }
    int harga, setrika, hargaFinal, inputUser;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconDollar = new javax.swing.JLabel();
        jenisLaundry = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputKilo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        tombolCalculate = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        tipeLaundry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 65, 110));

        iconDollar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        iconDollar.setForeground(new java.awt.Color(255, 255, 255));

        jenisLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothes", "Bedcover", "Footwear", "Rug" }));
        jenisLaundry.setToolTipText("Select your laundry");
        jenisLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaundryActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laundry");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Weight");

        inputKilo.setText("kg");
        inputKilo.setToolTipText("Input heavy of the laundry");
        inputKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKiloActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cost Per Kilos");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rp.");

        hargaLabel.setForeground(new java.awt.Color(255, 255, 255));

        tombolCalculate.setText("Calculate");
        tombolCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCalculateActionPerformed(evt);
            }
        });

        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        priceLabel.setText("Price will shown here after calculate");

        tipeLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wash Only", "Wash + Ironing" }));
        tipeLaundry.setToolTipText("Select the service");
        tipeLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipeLaundryActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type");

        backButton.setBackground(new java.awt.Color(0, 65, 110));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(0, 65, 110));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(iconDollar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombolCalculate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tipeLaundry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jenisLaundry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputKilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconDollar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jenisLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hargaLabel))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputKilo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tipeLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolCalculate)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        OpsiLayanan back = new OpsiLayanan();
        back.setVisible(true);
        back.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void tipeLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeLaundryActionPerformed
        if (tipeLaundry.getSelectedItem().toString().equalsIgnoreCase("Wash + Ironing")){
            setrika = 2000; priceLabel.setText("Price will shown here after calculate");}
        else if (tipeLaundry.getSelectedItem().toString().equalsIgnoreCase("Wash Only")){
            setrika = 0; priceLabel.setText("Price will shown here after calculate");}// TODO add your handling code here:
    }//GEN-LAST:event_tipeLaundryActionPerformed

    private void tombolCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCalculateActionPerformed
        try {
            String input = inputKilo.getText();
            inputUser = Integer.parseInt(input);
            hargaFinal = inputUser * harga;
            hargaFinal += (setrika * inputUser);
            if (hargaFinal == 0){
                priceLabel.setText("Please choose Laundry box!");
            } else if (hargaFinal == 2000){
                priceLabel.setText("Please choose Laundry box!");
            } else priceLabel.setText("Price: Rp." + hargaFinal);}
        catch (NumberFormatException e){
            priceLabel.setText("Input weight field first!");
        }//TODO add your handling code here:
    }//GEN-LAST:event_tombolCalculateActionPerformed

    private void inputKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKiloActionPerformed

    private void jenisLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisLaundryActionPerformed
        if (jenisLaundry.getSelectedItem().toString().equalsIgnoreCase("Clothes")){
            hargaLabel.setText("6.000");harga=6000;} else if (jenisLaundry.getSelectedItem().toString().equalsIgnoreCase("Bedcover")){
            hargaLabel.setText("8.000");harga=8000;} else if (jenisLaundry.getSelectedItem().toString().equalsIgnoreCase("Footwear")){
            hargaLabel.setText("7.000");harga=7000;} else if (jenisLaundry.getSelectedItem().toString().equalsIgnoreCase("Rug")){
            hargaLabel.setText("10.000");harga=10000;}// TODO add your handling code here:
    }//GEN-LAST:event_jenisLaundryActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
    int confirm = JOptionPane.showOptionDialog(this, "Proceed to print Payment Note?\nMake sure that price had shown", "Continue", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null,null );
    switch (confirm){
        case JOptionPane.YES_OPTION: //Iya
    //Transfer Variabel
        NotaPembayaran next = new NotaPembayaran();
    //Biodata Customer
        next.outputNama.setText(titipNama);
        next.outputAlamat.setText(titipAlamat);
        next.outputNomorHP.setText(titipHP);
    //Nota Harga
        next.outputBerat.setText(": " + inputKilo.getText() + " Kg");
        next.outputTipeLaundri.setText(": " + tipeLaundry.getSelectedItem().toString() + ", " + jenisLaundry.getSelectedItem().toString());

        String outputharga = "" + hargaFinal;
        next.outputHarga.setText(": Rp. " + outputharga);

    //Pindah Frame
        this.setVisible(false);
        next.setVisible(true);
        next.setLocationRelativeTo(null);
            break;
        case JOptionPane.NO_OPTION:
            break;
    }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulasiHargaLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulasiHargaLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulasiHargaLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulasiHargaLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulasiHargaLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JLabel iconDollar;
    private javax.swing.JTextField inputKilo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenisLaundry;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JComboBox<String> tipeLaundry;
    private javax.swing.JButton tombolCalculate;
    // End of variables declaration//GEN-END:variables
}
