/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundrydailyclean;

/**
 *
 * @author Lenovo
 */
public class NotaPembayaran extends javax.swing.JFrame {

    /**
     * Creates new form NotaPembayaran
     */
    public NotaPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lingkaranbawah = new javax.swing.JLabel();
        lingkaranatas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        beratLabel = new javax.swing.JLabel();
        hargalabel = new javax.swing.JLabel();
        tipelaundriLabel = new javax.swing.JLabel();
        finishbutton = new javax.swing.JButton();
        noHPLabel = new javax.swing.JLabel();
        outputBerat = new javax.swing.JLabel();
        outputTipeLaundri = new javax.swing.JLabel();
        outputHarga = new javax.swing.JLabel();
        outputNama = new javax.swing.JLabel();
        outputAlamat = new javax.swing.JLabel();
        outputNomorHP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lingkaranbawah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lingkaranbawah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documents\\PROJECT AKHIR\\New Project\\laundryteam3\\src\\main\\java\\Image\\lingkaran.png")); // NOI18N
        lingkaranbawah.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lingkaranatas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documents\\PROJECT AKHIR\\New Project\\laundryteam3\\src\\main\\java\\Image\\lingkaran.png")); // NOI18N
        lingkaranatas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 65, 110));
        jLabel3.setText("Payment Note");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 65, 110));
        namaLabel.setText("Name");

        alamatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(0, 65, 110));
        alamatLabel.setText("Address");

        beratLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        beratLabel.setForeground(new java.awt.Color(0, 65, 110));
        beratLabel.setText("Heavy");

        hargalabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hargalabel.setForeground(new java.awt.Color(0, 65, 110));
        hargalabel.setText("Total Cost");

        tipelaundriLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipelaundriLabel.setForeground(new java.awt.Color(0, 65, 110));
        tipelaundriLabel.setText("Type Laundry");

        finishbutton.setBackground(new java.awt.Color(0, 65, 110));
        finishbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        finishbutton.setForeground(new java.awt.Color(255, 255, 255));
        finishbutton.setText("Finish");
        finishbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishbuttonActionPerformed(evt);
            }
        });

        noHPLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noHPLabel.setForeground(new java.awt.Color(0, 65, 110));
        noHPLabel.setText("Phone");

        outputBerat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputBerat.setForeground(new java.awt.Color(0, 65, 110));
        outputBerat.setText(": ");

        outputTipeLaundri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputTipeLaundri.setForeground(new java.awt.Color(0, 65, 110));
        outputTipeLaundri.setText(": ");

        outputHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputHarga.setForeground(new java.awt.Color(0, 65, 110));
        outputHarga.setText(": ");

        outputNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputNama.setForeground(new java.awt.Color(0, 65, 110));
        outputNama.setText(": ");

        outputAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputAlamat.setForeground(new java.awt.Color(0, 65, 110));
        outputAlamat.setText(": ");

        outputNomorHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputNomorHP.setForeground(new java.awt.Color(0, 65, 110));
        outputNomorHP.setText(": ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lingkaranbawah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(lingkaranatas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatLabel)
                            .addComponent(namaLabel)
                            .addComponent(noHPLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outputAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outputNomorHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outputNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tipelaundriLabel)
                                        .addComponent(hargalabel)
                                        .addComponent(beratLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(outputBerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(outputTipeLaundri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(outputHarga)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lingkaranatas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noHPLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(outputNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputNomorHP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beratLabel)
                    .addComponent(outputBerat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipelaundriLabel)
                    .addComponent(outputTipeLaundri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargalabel)
                    .addComponent(outputHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(finishbutton)
                        .addGap(54, 54, 54))
                    .addComponent(lingkaranbawah, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JLabel beratLabel;
    private javax.swing.JButton finishbutton;
    private javax.swing.JLabel hargalabel;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lingkaranatas;
    private javax.swing.JLabel lingkaranbawah;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel noHPLabel;
    public javax.swing.JLabel outputAlamat;
    public javax.swing.JLabel outputBerat;
    public javax.swing.JLabel outputHarga;
    public javax.swing.JLabel outputNama;
    public javax.swing.JLabel outputNomorHP;
    public javax.swing.JLabel outputTipeLaundri;
    private javax.swing.JLabel tipelaundriLabel;
    // End of variables declaration//GEN-END:variables
}
